### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/wasm-talk#1]
# Motivation
We want to be able to host the app. This involves getting up all our dependencies.

# Tasks 
- [x] Get up dependencies.  
- [x] Be able to compile a basic webassembly file.
- [x] Be able to display the webassembly file in the front-end.
