### ISSUE TITLE
User can have a WASM vs JS test.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/wasm-talk#3]
# Motivation
We want to be able to be able to multiply 2 matrices together with webAssembly and JavaScript for comparison.

# Tasks
- [x] Be able to solve TaxiCab in WASM.
- [x] Be able to solve TaxiCab in JavaScript.
- [x] Show timer between the two.
